@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tech.anonymoushacker1279.immersiveweapons.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;