org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.3
minecraft_version_range=[26.3, 26.4)
neo_version=26.3.0.19-beta
neo_version_range=[26.3.0.19-beta,)
loader_version_range=[4,)
mod_id=immersiveweapons
mod_version=26.3-1.40.0
mod_group_id=tech.anonymoushacker1279.immersiveweapons
openportals_version=26.3-1.4.0
iwcb_version=26.2-1.16.0
terrablender_version=26.3-26.3.0.0.7
wthit_version=20.0.0
badpackets_version=0.12.2
jei_version=31.7.0.44