modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/ImmersiveWeapons/issues" #optional

[[mods]] #mandatory
modId = "immersiveweapons" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Immersive Weapons" #mandatory
displayURL = "https://github.com/AnonymousHacker1279/ImmersiveWeapons" #optional
logoFile = "logo.png" #optional
credits = "Written by AnonymousHacker1279 and visually designed with the help of Jonny-fox and gamingwarrior68 with pain and suffering" #optional
authors = "AnonymousHacker1279" #optional
description = '''
Immersive Weapons is a vanilla+ weapons add-on aiming to spice up your combat skills.
'''

[[dependencies.immersiveweapons]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[35,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.immersiveweapons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"