modLoader = "javafml" #mandatory
loaderVersion = "[38,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/ImmersiveWeapons/issues" #optional

[[mods]] #mandatory
modId = "immersiveweapons" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Immersive Weapons" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-weapons" #optional
updateJSONURL = "https://raw.githubusercontent.com/AnonymousHacker1279/ImmersiveWeapons/1.18.x-dev/update.json"
logoFile = "logo.png" #optional
credits = "Written by AnonymousHacker1279 and visually designed with the help of Jonny-fox and gamingwarrior68 with pain and suffering" #optional
authors = "AnonymousHacker1279" #optional
description = '''
Immersive Weapons is more than just a weapons mod aiming to spice up your combat skills.
'''

[[dependencies.immersiveweapons]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[38.0.0,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.immersiveweapons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"