@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tech.anonymoushacker1279.immersiveweapons.client.particle.wisp;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;