@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tech.anonymoushacker1279.immersiveweapons.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;