org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
neo_version=26.2.0.72
neo_version_range=[26.2.0.59,)
loader_version_range=[4.0,)
mod_id=iwcompatbridge
mod_version=26.2-1.16.0
mod_group_id=tech.anonymoushacker1279.iwcompatbridge
immersiveweapons_version=26.2-1.39.0
openportals_version=26.2-1.3.0
terrablender_version=26.2-26.2.0.0.2
wthit_version=20.0.0
badpackets_version=0.12.2
curios_version=16.0.0+26.2
jei_version=30.28.0.193