@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tech.anonymoushacker1279.immersiveweapons.client.particle.damage_indicator;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;